# 오리 농법

문제설명
농부 민겸이는 밭에서 농사를 짓습니다.
민겸이의 밭은 N × N 크기의 정사각형 모양입니다. 즉, N^2개의 1 × 1 크기의 땅으로 나눌 수 있습니다. 각 땅은 빈 땅, 작물만 있는 땅, 잡초만 있는 땅으로 구분됩니다. 민겸이는 잡초를 손쉽게 제거하기 위해 최첨단 오리 농법을 도입했습니다.
오리 인덕이는 식탐이 많기 때문에 민겸이가 정한 어떤 가로줄 또는 세로줄의 잡초와 작물을 모두 먹습니다. 인덕이가 먹을 수 있는 양에 한계는 없고, 민겸이는 인덕이를 원하는 만큼 이용할 수 있습니다.
똑똑한 민겸이는 인덕이를 적절히 이용하여 모든 작물을 보존하면서 최대한 많은 잡초를 없앴습니다. 이때 잡초만 있는 땅이 몇 개 남아있는지 알아봅시다.

입출력 예

입력 #1

4

1 0 1 0

0 2 0 2

2 0 0 0

2 1 2 2

입력 #2

4

0 0 1 2

1 2 0 2

0 0 0 1

2 1 0 0

입력값 설명

입력은 여러 개의 줄로 주어집니다.
첫 번째 줄에는 밭의 가로와 세로의 길이?N이 주어집니다. (1 ≤ N ≤ 5)
두 번째 줄부터 N개의 줄에는 밭의 정보가 공백으로 구분되어 주어집니다. 0은 빈 땅, 1은 작물만 있는 땅, 2는 잡초만 있는 땅입니다.

출력 #1

2

출력 #2

4

출력값 설명

남아있는 잡초만 있는 땅이 몇 개인지 출력합니다.

# 문제 접근 

- 최대한 많은 농작물을 보호 = 1이 있는 행 또는 열에는 오리를 놓지 않음 
- 행 또는 열에 1이 없으면 0으로 초기화

- 넘파이 2차원 배열을 사용 


In [9]:
import numpy as np
n = int(input())

M_list = []

for i in range(n):
    m = list(map(int,input().split()))
    M_list.append(m)

MM = np.array(M_list)
#print(1,MM)
# 행 검사
for i in range(n):
    for j in range(n):
        if 1 in MM[i][:]:#  행 내에 1 작물이 있으면 skip
            pass
        else: 
            if MM[i][j]==2:
                MM[i][j]=0

MM_T = MM.T
#print(2,MM_T)
# 열 검사 
for i in range(n):
    for j in range(n):
        if 1 in MM_T[i][:]:#  행 내에 1 작물이 있으면 skip
            pass
        else: 
            if MM_T[i][j]==2:
                MM_T[i][j]=0
          
cnt = 0                
for i in range(n):
    for j in range(n):
        if MM_T[i][j] == 2:
            cnt+=1

print(cnt)

1 [[1 0 1 0]
 [0 2 0 2]
 [2 0 0 0]
 [2 1 2 2]]
2 [[1 0 0 2]
 [0 0 0 1]
 [1 0 0 2]
 [0 0 0 2]]
2


In [18]:
# 넘파이를 사용하지 않는 방법 
n = int(input())

M_list = []

for i in range(n):
    m = list(map(int,input().split()))
    M_list.append(m)

MM = np.array(M_list)
print(1,MM)
# 행 검사
for i in range(n):
    for j in range(n):
        if 1 in MM[i][:]:#  행 내에 1 작물이 있으면 skip
            pass
        else: 
            if MM[i][j]==2:
                MM[i][j]=0


# 열 검사 
for i in range(n):
    for j in range(n):
        if 1 in MM[:][i]:#  열 내에 1 작물이 있으면 skip
            pass
        else: 
            if MM[j][i]==2:
                MM[j][i]=0
      
print(MM)    
cnt = 0                
for i in range(n):
    for j in range(n):
        if MM[i][j] == 2:
            cnt+=1

print(cnt)

1 [[1 0 1 0]
 [0 2 0 2]
 [2 0 0 0]
 [2 1 2 2]]
[[1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [2 1 0 2]]
2
