<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/></center>

# 학습 목표

- Numpy 배열의 기본 개념을 이해합니다.
- 1차원, 2차원, 3차원 배열을 만들 수 있습니다.
- Reshape 기능을 사용해 배열 형태를 바꿀 수 있습니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.
- 배열 사이의 기본적인 연산을 수행할 수 있습니다.

# 1.라이브러리 불러오기

- Numpy 배열을 사용하려면 우선 **numpy** 라이브러리를 불러와야 합니다.
- numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [6]:
# 라이브러리 불러오기
import numpy as np

### [참고] 왜 배열?

**문제1**: 다음 리스트 각 요소에 2를 곱하세요.

In [10]:
# 리스트
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 2 곱하기?
a = a * 2

# 확인
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**문제2**: 다음 리스트 요소 중에서 짝수만 표시하세요.

In [13]:
# 리스트
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# 짝수만 표시...몰라요ㅜ.ㅜ
for i in a:
    if i %2 ==0:
        print(i,end=' ' )

2 4 6 8 

**문제3**: 다음 배열 각 요소에 2를 곱하세요.

In [15]:
# 배열
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 확인
print(a)

# 2 곱하기
a *=2

# 확인
print(a)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


**문제4**: 다음 배열 요소 중에서 짝수만 표시하세요.

In [ ]:
# 배열
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 확인
print(a)

# 짝수만 표시


# 2.배열 만들기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합니다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

## 2.1.용어 정의

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array
- shape는 (3, 4)

## 2.2.배열 만들기

- **np.array() 함수**를 사용해서 배열을 만듭니다.
- 대부분 **리스트**로부터 배열을 만들거나, 머신러닝 관련 함수 결괏값이 배열이 됩니다.

### 2.2.1.배열 만들기

**1) 1차원 배열 만들기**

In [25]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

[1 2 3 4 5]


**2) 2차원 배열 만들기**

In [28]:
# 2차원 리스트
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2],
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

[[1.5 2.5 3.2]
 [4.2 5.7 6.4]]


**3) 3차원 배열 만들기**

In [31]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)
print(np.shape(b3))

[[[1 3 1]
  [4 7 6]
  [8 3 4]]

 [[6 2 4]
  [8 1 5]
  [3 5 9]]]
(2, 3, 3)


### 2.2.2.배열 정보 확인

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

**1) 차원 확인**

- ndim 속성으로 배열 차원을 확인합니다.

In [35]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)


1
2
3


**2) 형태(크기) 확인**

- shape 속성으로 배열 형태를 확인합니다.
- 결과는 다음과 같은 형태의 튜플로 표시됩니다.
    - 1차원: (x, )
    - 2차원: (x, y)
    - 3차원: (x, y, z)
- 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [38]:
# 형태(크기) 확인
print(b1.shape)
print(b2.shape)
print(b3.shape)

(5,)
(2, 3)
(2, 3, 3)


**3) 요소 자료형 확인**

- dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다.
- 배열은 한 가지 자료형만 가질 수 있다는 특징이 있습니다.

In [40]:
# 요소 자료형 형식 확인
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)



int32
float64
int32


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [48]:
# 10, 11, 12, 13, 14, 15

# 배열 만들기
arr = np.array([10,11,12,13,14,15])

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)



[10 11 12 13 14 15]
1
(6,)
int32


[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요

In [50]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
arr = np.array(a)

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)



[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
2
(3, 4)
int32


### 2.2.3.Reshape

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 2) → (2, 3) → (1, 6) → (6, 1) 등등 요소 개수만 변하지 않으면 됩니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/array4.png' width=550 align="left"/>

In [54]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]]


**1) (2, 3) → (3, 2)**

In [65]:
# (3, 2) 형태의 2차원 배열로 Reshape numpy 라이브러리 사용

#  np.reshape 는 다른 자료형도 변환시킬 수 있다
b = np.reshape(a,(3,2))

# 확인
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# (3, 2) 형태의 2차원 배열로 Reshape
# a 에만 적용 가능함 
b = a.reshape(3,2)

# 확인
print(b)

**2) (2, 3) → (6,)**

In [61]:
# 1차원 배열로 Reshape
c = b.reshape(6,)

# 확인
print(c)

[1 2 3 4 5 6]


**3) -1의 편리성**

- **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

In [63]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능

# ex 2522263365개 로구성된 리스트를 N x ? 로 만들고 싶음 , >> reshape(n , -1) 하면 단순계산끝 
print(a.reshape(1, -1))
print(a)

print(a.reshape(2, -1))
print(a)

print(a.reshape(3, -1))
print(a)

#print(a.reshape(4, ?))
#print(a.reshape(5, ?))

print(a.reshape(6,-1))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음에 주어진 배열의 형태(shape)를 확인한 후 요구되는 형태로 바꿔 보세요.

In [67]:
# 배열 만들기
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)

# (4, ?))형태의 2차원 배열 a1
a1 = np.reshape(a,(4,-1))

# 확인
print(a1)

# (2, ?) 형태의 2차원 배열 a2
a1 = np.reshape(a,(2,-1))

# 확인
print(a1)

(3, 4)
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[11 12 13 14 15 16]
 [17 18 19 20 21 22]]


# 3.배열 인덱싱과 슬라이싱

- 지금까지 다룬 자료형들 보다 배열 인덱싱과 슬라이싱이 조금 어렵습니다.

### 3.1.인덱싱

- 1차원 배열은 리스트와 방법이 같으므로 설명을 생략합니다.
- **배열[행, 열]** 형태로 특정 위치의 요소를 조회합니다.
- **배열[[행1,행2,..], :]** 또는 **배열[[행1,행2,..]]** 형태로 특정 행을 조회합니다.
- **배열[:, [열1,열2,...]]** 형태로 특정 열을 조회합니다.
- **배열[[행1,행2,...], [열1,열2,...]]** 형태로 특정 행의 특정 열을 조회합니다.

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 확인
print(a)

**1) 요소 조회**

In [ ]:
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])

**2) 행 조회**

In [ ]:
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])
print(a[[0, 1]])

In [ ]:
# 첫 번째, 두 번째, 세 번째 행 조회
# print(a[[0, 1, 2], :])
print(a[[0, 1, 2]])

**3) 열 조회**

In [ ]:
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])

**4) 행, 열 조회**

In [ ]:
# 배열 확인
print(a)

In [ ]:
# 두 번째 행 두 번째 열의 요소 조회
print(a[[1], [1]])

In [ ]:
# 세 번째 행 두 번째 열의 요소 조회
print(a[[2], [1]])

In [ ]:
# 첫 번째 행 첫 번째 열, 두 번째 행 두 번째 열의 요소 조회
print(a[[0, 1], [0, 1]])

In [ ]:
# 첫 번째 행 첫 번째 열, 두 번째 행 두 번째 열, 세 번째 행 첫 번째 열의 요소 조회
print(a[[0, 1, 2], [0, 1, 0]])

### 3.2.슬라이싱

- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 조회 결과는 **2차원 배열**이 됩니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:M, 2:N]** 이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 됩니다.

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 확인
print(a)

In [ ]:
# 첫 번째 ~ 두 번째 행 조회
# print(a[0:2, :])
print(a[0:2])

In [ ]:
# 첫 번째 행, 첫 번째 ~ 두 번째 열 조회
print(a[0, 0:2])

In [ ]:
# 첫 번째 ~ 세 번째 행, 두 번째 ~ 세 번째 열 조회
print(a[0:3, 1:3])

In [ ]:
# 두 번째 ~ 끝 행, 두 번째 ~ 끝 열 조회
print(a[1:, 1:])

**[참고] 배열 인덱싱 & 슬라이싱**

<img src='https://raw.githubusercontent.com/jangrae/img/master/array2.png' width=700 align = "left"/>

### 3.3.조건 조회

- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부릅니다.
- 조회 결과는 **1차원 배열**이 됩니다.

In [69]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]


- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회합니다.

In [72]:
# 요소 중에서 90 이상인 것만 조회
print(score[score>=90])

[91 93 96 91]


- 검색 조건을 변수로 선언해 사용할 수 있습니다.

In [74]:
# 요소 중에서 90 이상인 것만 조회
c = score>=90

print(score[c])


[91 93 96 91]


- 여러 조건을 **&** 와 **|** 로 연결하여 조회할 수 있습니다.

In [82]:
# 모든 요소 중에서 90 이상 95 미만인 것만 조회
c = (score>=90) & (score <95)

print(score[c])


[91 93 91]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

[문1] 다음 배열에서 짝수만 추출해 보세요.

In [76]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회

print( score [score %2 ==0])

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]
[78 84 82 96]


## 4.배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 약간의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

**[참고] 배열 연산**

<img src='https://raw.githubusercontent.com/jangrae/img/master/array3.png' width=600 align = "left"/>

In [86]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


**1) 배열 더하기**

- \+ 또는 **dp.add()** 함수를 사용합니다.

In [89]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


**2) 배열 빼기**

- \- 또는 **np.subtract()** 함수를 사용합니다.

In [92]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


**3) 배열 곱하기**

- \* 또는 **np.multiply()** 함수를 사용합니다.

In [95]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


**4) 배열 나누기**

- \/ 또는 **np.divide()** 함수를 사용합니다.

In [98]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**5) 배열 제곱**

- \** 또는 **np.power()** 함수를 사용합니다.

In [101]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


In [103]:
# 배열 제곱
print(x ** 2)

[[ 1  4]
 [ 9 16]]
