<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/></center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# [실습] 배열 만들기

1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [ ]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

np_arr =  np.array([[  1  2  3],[  4  5  6],[  7  8  9], [ 10 11 12]]) 

3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

4) np_arr 배열을 아래 주어진 4 X 3 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [ ]:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]


5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.

In [ ]:
# 조건 조회
print(np_arr[np_arr > 7])

8) 위의 실습에서 선택된 요소들의 값을 모두 2배로 만드세요.

9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

10) np_arr 배열의 요소들 중에서 홀수인 요소만 조회해서 a 라는 리스트로 선언하고 확인하세요.