<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/iris2.png?raw=true" width=800 align="left"/>

# 실습 내용

- Iris 데이터로 모델링합니다.
- Logistic Regression 알고리즘으로 모델링합니다.


# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [5]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%config InlineBackend.figure_format='retina'

In [6]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/iris.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [8]:
# 상위 몇 개 행 확인
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
# 기초통계량 확인
data.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:
# 범주값 개수 확인
data['Species'].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [11]:
# 상관관계 확인
data.corr(numeric_only=True)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.000000    -0.117570      0.871754     0.817941
Sepal.Width      -0.117570     1.000000     -0.428440    -0.366126
Petal.Length      0.871754    -0.428440      1.000000     0.962865
Petal.Width       0.817941    -0.366126      0.962865     1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) x, y 분리**

In [14]:
# target 확인
target = 'Species'
# 데이터 분리
x = data.drop(columns = target)
y= data.loc[:,target]


**2) 학습용, 평가용 데이터 분리**

In [16]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split
# 7:3으로 분리
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state = 1 , stratify = y)


# 4.모델링

- 본격적으로 모델을 선언하고 학습하고 평가하는 과정을 진행합니다.

In [18]:
# 1단계: 불러오기
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report


In [19]:
# 2단계: 선언하기
# Softmax 기반 다중 클래스 로지스틱 회귀 모델 학습
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)

In [20]:
# 3단계: 학습하기
model.fit(x_train, y_train)

LogisticRegression(max_iter=200, multi_class='multinomial')

In [21]:
# 4단계: 예측하기
y_pred = model.predict(x_test)

In [22]:
# 5단계: 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.93      1.00      0.96        13
   virginica       1.00      0.92      0.96        13

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [23]:
# 회귀계수
print(list(x))
print(model.coef_.round(3))
print(model.intercept_.round(3))

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']
[[-0.461  0.84  -2.318 -0.978]
 [ 0.124 -0.284 -0.091 -0.62 ]
 [ 0.337 -0.556  2.409  1.598]]
[  9.56    3.493 -13.053]


In [24]:
#z 값 확인 > 나중에 시그모이드를 통과하면 확률로 변함 0 1 
z =model.decision_function(x_test)
print(z[:10].round(3))

[[-4.511  1.796  2.715]
 [ 6.44   2.888 -9.328]
 [ 6.709  2.881 -9.591]
 [ 6.3    2.854 -9.154]
 [ 0.562  2.54  -3.102]
 [ 6.588  2.926 -9.513]
 [-1.489  2.227 -0.738]
 [-2.69   1.928  0.762]
 [ 6.526  3.048 -9.573]
 [-2.762  2.112  0.649]]


In [25]:
# 로지스틱 함수 사용 (0 , 1 target이 2개의 범주만 가질때 )
#from scipy.special import expit 
#print(expit(z)[:10].round(3))

# 소프트맥스 함수 사용 target이 3개 이상의 범주를 가질때 
from scipy.special import softmax
print(softmax(z,axis=1)[:5].round(3))

[[0.001 0.285 0.714]
 [0.972 0.028 0.   ]
 [0.979 0.021 0.   ]
 [0.969 0.031 0.   ]
 [0.121 0.876 0.003]]


In [26]:
# y_pred값 확인 
print(y_pred[:5]) # 0.5 보다 크면 1 아니면 0 

['virginica' 'setosa' 'setosa' 'setosa' 'versicolor']
