<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/attrition.png?raw=true" width=800 align="left"/>

# 실습 내용

- 다양한 알고리즘으로 성능이 최적화된 모델을 만듭니다.
- 성능이 좋을 것으로 예상되는 모델을 선정해 평가를 진행합니다.

# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [5]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [6]:
# https://raw.githubusercontent.com/jangrae/csv/master/Attrition_simple2.csv

path = 'https://raw.githubusercontent.com/jangrae/csv/master/Attrition_simple2.csv'
data = pd.read_csv(path)


# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

**데이터 설명**

- **Attrition: 이직 여부 (1: 이직, 0: 잔류) - Target**
- Age: 나이
- DistanceFromHome: 집-직장 거리 (단위: 마일)
- EmployeeNumber: 사번
- Gender: 성별 (Male, Female)
- JobSatisfaction: 직무 만족도(1: Low, 2: Medium, 3: High, 4: Very High)
- MaritalStatus: 결혼 상태 (Single, Married, Divorced)
- MonthlyIncome: 월급 (단위: 달러)
- OverTime: 야근 여부 (Yes, No)
- PercentSalaryHike: 전년 대비 급여 인상율(단위: %)
- TotalWorkingYears: 총 경력 연수

In [9]:

#데이터 확인 
data.head()

Attrition  Age  DistanceFromHome  EmployeeNumber  Gender  JobSatisfaction  \
0          0   33                 7             817    Male                3   
1          0   35                18            1412    Male                4   
2          0   42                 6            1911    Male                1   
3          0   46                 2            1204  Female                1   
4          1   22                 4             593    Male                3   

  MaritalStatus  MonthlyIncome OverTime  PercentSalaryHike  TotalWorkingYears  
0       Married          11691       No                 11                 14  
1        Single           9362       No                 11                 10  
2       Married          13348       No                 13                 18  
3       Married          17048       No                 23                 28  
4        Single           3894       No                 16                  4

In [10]:
#기술통계 확인
data.describe().T


count         mean          std     min      25%     50%  \
Attrition          1196.0     0.163043     0.369560     0.0     0.00     0.0   
Age                1196.0    36.943980     9.092700    18.0    30.00    36.0   
DistanceFromHome   1196.0     9.258361     8.166016     1.0     2.00     7.0   
EmployeeNumber     1196.0  1035.629599   604.340130     1.0   507.75  1028.0   
JobSatisfaction    1196.0     2.716555     1.110962     1.0     2.00     3.0   
MonthlyIncome      1196.0  6520.104515  4665.902253  1009.0  2928.25  4973.5   
PercentSalaryHike  1196.0    15.251672     3.625946    11.0    12.00    14.0   
TotalWorkingYears  1196.0    11.330268     7.823821     0.0     6.00    10.0   

                       75%      max  
Attrition             0.00      1.0  
Age                  43.00     60.0  
DistanceFromHome     14.00     29.0  
EmployeeNumber     1581.25   2068.0  
JobSatisfaction       4.00      4.0  
MonthlyIncome      8420.50  19999.0  
PercentSalaryHike    18.00     25.0  
TotalWorkingYears    15.00     40.0

In [11]:
#결측치 확인 
data.isna().sum()


Attrition            0
Age                  0
DistanceFromHome     0
EmployeeNumber       0
Gender               0
JobSatisfaction      0
MaritalStatus        0
MonthlyIncome        0
OverTime             0
PercentSalaryHike    0
TotalWorkingYears    0
dtype: int64

In [12]:
#
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Attrition          1196 non-null   int64 
 1   Age                1196 non-null   int64 
 2   DistanceFromHome   1196 non-null   int64 
 3   EmployeeNumber     1196 non-null   int64 
 4   Gender             1196 non-null   object
 5   JobSatisfaction    1196 non-null   int64 
 6   MaritalStatus      1196 non-null   object
 7   MonthlyIncome      1196 non-null   int64 
 8   OverTime           1196 non-null   object
 9   PercentSalaryHike  1196 non-null   int64 
 10  TotalWorkingYears  1196 non-null   int64 
dtypes: int64(8), object(3)
memory usage: 102.9+ KB


In [13]:
#



# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) 변수 제거**

In [16]:
# EmployeeNumber 
data.drop(columns= 'EmployeeNumber',inplace = True)
data.head()

Attrition  Age  DistanceFromHome  Gender  JobSatisfaction MaritalStatus  \
0          0   33                 7    Male                3       Married   
1          0   35                18    Male                4        Single   
2          0   42                 6    Male                1       Married   
3          0   46                 2  Female                1       Married   
4          1   22                 4    Male                3        Single   

   MonthlyIncome OverTime  PercentSalaryHike  TotalWorkingYears  
0          11691       No                 11                 14  
1           9362       No                 11                 10  
2          13348       No                 13                 18  
3          17048       No                 23                 28  
4           3894       No                 16                  4

**2) x, y 분리**

In [18]:
target = 'Attrition'
x = data.drop(columns = target)
y = data.loc[:,target]


**2) 가변수화**

In [20]:
dummy_cols = ['Gender','JobSatisfaction','MaritalStatus','OverTime']

x = pd.get_dummies(data=x , columns = dummy_cols , drop_first = True , dtype = int )
x.head()# light xbm을 위해서라도 문자열이 있어선 안된다 

Age  DistanceFromHome  MonthlyIncome  PercentSalaryHike  TotalWorkingYears  \
0   33                 7          11691                 11                 14   
1   35                18           9362                 11                 10   
2   42                 6          13348                 13                 18   
3   46                 2          17048                 23                 28   
4   22                 4           3894                 16                  4   

   Gender_Male  JobSatisfaction_2  JobSatisfaction_3  JobSatisfaction_4  \
0            1                  0                  1                  0   
1            1                  0                  0                  1   
2            1                  0                  0                  0   
3            0                  0                  0                  0   
4            1                  0                  1                  0   

   MaritalStatus_Married  MaritalStatus_Single  OverTime_Yes  
0                      1                     0             0  
1                      0                     1             0  
2                      1                     0             0  
3                      1                     0             0  
4                      0                     1             0

**3) 학습용, 평가용 데이터 분리**

In [22]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.3)


**4) 정규화**

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)

x_train_s = scaler.transform(x_train)
x_test_s = scaler.transform(x_test)



# 4.모델링

- 하이퍼파라미터 최적화 과정을 통해 최선의 성능을 갖는 모델을 만들고 성능을 검증합니다.
- 각 모델을 joblib.dump() 함수를 사용해 저장합니다.

In [26]:
# xgboost 설치
# !pip install xgboost

In [27]:
# lightgbm 설치
# !pip install lightgbm

- 이후 사용할 함수를 모두 불러옵니다.

In [29]:
# 분류(이직 여부를 예측)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

# 모델마다 최적의 파라미터를 찾아 학습
from sklearn.model_selection import GridSearchCV

# 모델 성능 평가
from sklearn.metrics import * 



**1) KNN**

- 최적으로 파라미터로 학습된 KNN 모델을 만들고, 최고의 파라미터와 성능을 확인합니다.
- 모델 이름은 model_knn으로 지정합니다.

In [31]:
# GridSearch 를 적용한 최적 모델을 확인 
param = {'n_neighbors': range(1, 21, 1)}
model_knn = GridSearchCV(KNeighborsClassifier(),param,cv = 5)
model_knn.fit(x_train_s, y_train) # (전체 학습)
# 예측 결과 확인
print('best params : ',model_knn.best_params_)
print('best_score : ',model_knn.best_score_) 

# # 2. 최적의 파라미터를 적용한 모델로 학습
# best_knn_model = model_knn.best_estimator_

# 3. x_test 데이터로 예측
y_pred = model_knn.predict(x_test_s)

# 4. 예측 성능 평가 (예: 정확도)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")

best params :  {'n_neighbors': 19}
best_score :  0.8387225548902195
Test Accuracy: 0.8607242339832869


**2) Decision Tree**

- 최적으로 파라미터로 학습된 Decision Tree 모델을 만들고, 최고의 파라미터와 성능을 확인합니다.
- 모델 이름은 model_dst로 지정합니다.

In [33]:
param = {'max_depth': range(1, 21, 1)}
model_dst = GridSearchCV(DecisionTreeClassifier(), param, cv = 5)
model_dst.fit(x_train, y_train) # (전체 학습)

# 예측 결과 확인
print('best params : ',model_dst.best_params_)
print('best_score : ',model_dst.best_score_) 

# # 2. 최적의 파라미터를 적용한 모델로 학습 (최적파라미터만 적용한 모델만 학습)
# best_dst_model = model_dst.best_estimator_

# 3. x_test 데이터로 예측
y_pred = model_dst.predict(x_test)

# 4. 예측 성능 평가 (예: 정확도)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")


best params :  {'max_depth': 3}
best_score :  0.8483105218135158
Test Accuracy: 0.8467966573816156


**3) Random Forest**

- 최적으로 파라미터로 학습된 Random Forest 모델을 만들고, 최고의 파라미터와 성능을 확인합니다.
- 모델 이름은 model_rdf로 지정합니다.

In [35]:
param = {
    'max_depth': range(1, 21, 1)
}
model_rf = GridSearchCV(DecisionTreeClassifier(), param, cv = 5)
model_rf.fit(x_train, y_train)

# 예측 결과 확인
print('best params : ',model_rf.best_params_)
print('best_score : ',model_rf.best_score_) 

# # 2. 최적의 파라미터를 적용한 모델로 학습
# best_rf_model = model_rf.best_estimator_

# 3. x_test 데이터로 예측
y_pred = model_rf.predict(x_test)

# 4. 예측 성능 평가 (예: 정확도)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")


best params :  {'max_depth': 4}
best_score :  0.84947248360422
Test Accuracy: 0.841225626740947


**4) LightGBM**

- 최적으로 파라미터로 학습된 LightGBM 모델을 만들고, 최고의 파라미터와 성능을 확인합니다.
- 모델 이름은 model_lgb로 지정합니다.

In [37]:
param = {'max_depth': range(1, 21, 1), 
         'n_estimators': range(50, 100, 10)}
model_lgbm = GridSearchCV(LGBMClassifier(verbose=-1), param , cv= 5)
model_lgbm.fit(x_train, y_train)

# 예측 결과 확인
print('best params : ',model_lgbm.best_params_)
print('best_score : ',model_lgbm.best_score_) 

# # 2. 최적의 파라미터를 적용한 모델로 학습
# best_lgbm_model = model_lgbm.best_estimator_

# 3. x_test 데이터로 예측
y_pred = model_lgbm.predict(x_test)

# 4. 예측 성능 평가 (예: 정확도)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")




best params :  {'max_depth': 2, 'n_estimators': 90}
best_score :  0.8614128885086968
Test Accuracy: 0.8495821727019499


# 5.성능평가

- 가장 좋은 성능을 보일 것으로 예상되는 모델로 평가를 진행합니다.

In [40]:
# KNN 성능평가
y_pred = model_knn.predict(x_test_s)

# 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[306   2]
 [ 48   3]]
              precision    recall  f1-score   support

           0       0.86      0.99      0.92       308
           1       0.60      0.06      0.11        51

    accuracy                           0.86       359
   macro avg       0.73      0.53      0.52       359
weighted avg       0.83      0.86      0.81       359



In [48]:
# Decision Tree 성능평가
y_pred = model_dst.predict(x_test)

# 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[296  12]
 [ 43   8]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91       308
           1       0.40      0.16      0.23        51

    accuracy                           0.85       359
   macro avg       0.64      0.56      0.57       359
weighted avg       0.81      0.85      0.82       359



In [46]:
# Random Forest 모델 평가 
y_pred = model_rf.predict(x_test)

# 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[294  14]
 [ 43   8]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       308
           1       0.36      0.16      0.22        51

    accuracy                           0.84       359
   macro avg       0.62      0.56      0.57       359
weighted avg       0.80      0.84      0.81       359



In [44]:
# light GBM 모델 평가
y_pred = model_lgbm.predict(x_test)

# 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[299   9]
 [ 45   6]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       308
           1       0.40      0.12      0.18        51

    accuracy                           0.85       359
   macro avg       0.63      0.54      0.55       359
weighted avg       0.80      0.85      0.81       359

